EstructurasDatosProyecto2/EstructurasDatosProyecto2/Controllers/ArchivosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EstructurasDatosProyecto2.Models;
using System.Web.Script.Serialization;

namespace EstructurasDatosProyecto2.Controllers
{
    public class direc
    {
        public int id { get; set; }
        public string text { get; set; }
        public DateTime creacion { get; set; }

    }
    [Authorize]
    public class ArchivosController : Controller
    {
        public static List<DirectoriosModelo> ParaBuscar = new List<DirectoriosModelo>();
    
    estructura2Entities bd = new estructura2Entities();
        public static int IdDirectorioPadre = 1;//el id por defecto del directorio padre sera siempre 1
        public static int DirectorioEliminar = 0;
        // GET: Archivos


        public ActionResult Index()
        {
            //para llenar la lista por primera vez
            init();
            return View();
        }
        //crea un directorio
        public ActionResult _CrearDir()
        {
            var lista = from s in bd.directorios
                        where s.estado == 1
                        select new DirectoriosModelo
                        {
                            id = s.id,
                            nombre = s.nombre
                        };



            ViewBag.listaDirectorios = new SelectList(lista.ToList(), "id", "nombre");
            return PartialView();
        }
        [HttpPost]
        public ActionResult _CrearDir(DirectoriosModelo dir)
        {
            directorio newdir = new directorio();
            newdir.nombre = dir.nombre;
            newdir.padre = IdDirectorioPadre;
            newdir.estado = 1;
            newdir.fecha_creacion = DateTime.Now;
            bd.directorios.Add(newdir);
            if (bd.SaveChanges() > 0)
            {
                return PartialView("Exito");
            }
            return View();
        }
        public ActionResult Exito()
        {
            return View();
        }
        public ActionResult _ListarDirectorios()
        {
            return PartialView();
        }

             //este metodo es temporal ya que solo guarda el id del directorio padre

        public void temp(int id)
        {
            IdDirectorioPadre = id;

        }
        public void combotem(int id)
        {
            DirectorioEliminar = id;

        }
        //metodo de ayuda para generar los hijos de los directorios aun no funciona
        public int[] child(int itm)
        {
            var dato = from s in bd.directorios
                       where s.padre == itm
                       select new DirectoriosModelo
                       {
                           id = s.id,
                           
                       };
            dato.ToList();
            int[] listahijos = new int[dato.Count()];
            int i = 0;
            foreach (var it in dato)
            {
                listahijos[i]=it.id;
                i++;
            }
                 

            return listahijos;
        }

        //desde la vista se llama este metodo para generar un json 
        public JsonResult llamarjson()
        {
            //En realidad solo estamos ocupando esta linea para obtener la lista de directorios
            var salida = llenarDirectorios();
            List<direc> objeto = new List<direc>();
            //int[] lista = new int[salida.Count];

            //int i = 0;
            //foreach (var item in salida)
            //{
            //    lista = child(item.id);
            //    if (lista.Length>0)
            //    {
            //        for (int j=0;j<lista.Length;j++)
            //        {
            //            if (lista[j]!=0)
            //            {
            //                var ob = new dir
            //                {
            //                    id = item.id,
            //                    text = item.nombre,
            //                    child = new children
            //                    {
            //                        id = lista[j],
            //                        text=BuscarNombre(lista[j])
            //                    }
            //                };
            //                objeto.Add(ob);                       }
            //            else
            //            {
            //                continue;
            //            }
            //        }
            //    }
            //    else
            //    {
            //        var ob = new dir
            //        {
            //            id = item.id,
            //            text = item.nombre
            //        };
            //        objeto.Add(ob);
            //    }

            //}

            //este es el formato que se busca para el json
            // [{"id":1,"text":"Root node","children":[{"id":2,"text":"Child node 1"},{"id":3,"text":"Child node 2"}]}]

            foreach (var item in salida)
            {
                objeto.Add(new direc() {id=item.id,text=item.nombre,creacion=item.fecha_creacion.Value});
            }

            return Json(objeto, JsonRequestBehavior.AllowGet);
        }

        //llena la lista de directorios
        private List<DirectoriosModelo> llenarDirectorios()
        {
            var it = from s in bd.directorios
                     where s.estado == 1
                     select new DirectoriosModelo
                     {
                         id = s.id,
                         nombre = s.nombre,
                         padre = s.padre,
                         estado = s.estado,
                         fecha_creacion = s.fecha_creacion

                     };
            return it.ToList();
        }

        //Este metodo es temporal, busca llenar una lista para no estarla pidiendo a la base de datos
        //se debe buscar una opcion mejor
        public void init()
        {
            if (ParaBuscar.Count()==0)
            {
                var it = from s in bd.directorios
                         where s.estado == 1
                         select new DirectoriosModelo
                         {
                             id = s.id,
                             nombre = s.nombre,
                             padre = s.padre,
                             estado = s.estado,
                             fecha_creacion = s.fecha_creacion

                         };
                it.ToList();
                foreach (var i in it)
                {
                    ParaBuscar.Add(new DirectoriosModelo() { id = i.id, nombre = i.nombre, padre = i.padre });
                }
            }        

        }


        public ActionResult _solicitudArchivo(string idDatos)
        {
            int id = 1;//por defecto mostrara los archivos de la raiz
            try
            {
                id = Convert.ToInt32(idDatos);
            }
            catch (Exception)
            {
               
            }

            var lista = from s in bd.archivoes
                        where s.id_directorio==id
                        select new ArchivoModelo
                        {
                            id = s.id,
                            nombre = s.nombre,
                            tipo = s.tipo,
                            fecha_creacion = s.fecha_creacion,
                            id_directorio = s.id_directorio,
                            datos = s.datos
                        };
       
            return PartialView(lista.ToList());
        }

        public string BuscarNombre(int id)
        {
            foreach (var item in ParaBuscar)
            {
                if (item.id.Equals(id))
                {
                    return item.nombre;
                }
            }

            return null;
        }

        [HttpPost]
        public ActionResult _EliminarDirectorio(DirectoriosModelo dir)
        {
      
            return View();
        }

        public ActionResult _EliminarDirectorio()
        {
            List<DirectoriosModelo> disponibles = new List<DirectoriosModelo>();
            
            var lista = from s in bd.directorios
                        select new DirectoriosModelo
                        {
                            id = s.id,
                            nombre = s.nombre,
                            padre = s.padre,
                            estado = s.estado,
                            fecha_creacion = s.fecha_creacion

                        };
            lista.ToList();
            //esta parte solo retorna los directorios que no tienen hijos
            int[] padres = new int[lista.Count()+1];
            int i = 0;
            foreach (var item in lista)
            {
                padres[i] = item.padre.Value;
                i++;
            }
            int bande = 0;
            foreach (var it in lista)
            {
                bande = 0;
                for (int l=0;l<padres.Length;l++)
                {
                    
                    if (it.id.Equals(padres[l]))
                    {
                        bande++;
                    }
                }
                if (bande==0)
                {
                    disponibles.Add(new DirectoriosModelo() { id = it.id, nombre = it.nombre });

                }
                //int band = 0;
                //for (int k=0;k<padres.Length;k++)
                //{
                //    if (it.padre.Value == padres[k])
                //    {
                //        band++;
                //    }
                //}
                //if (band == 0)
                //{
                //    disponibles.Add(new DirectoriosModelo() { id = it.id, nombre = it.nombre });
                //}

            }

            ViewBag.listaDir = new SelectList(disponibles, "id", "nombre");
            return PartialView();
        }

        public ActionResult EliminarCarpeta()
        {

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/EliminarCarpeta.cshtml
@model EstructurasDatosProyecto2.Models.dropboxdirectoriosModelo
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@{
    ViewBag.Title = "Eliminar Carpeta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Carpeta</h2>

@if (ViewBag.listacarp != null)
{
	@Html.DropDownListFor(model => model.id, ViewBag.listacarp as SelectList, "-----Seleccionar Directorio", new { @class = "form-control" })

}

<input class="btn btn-warning" type="button" name="miboton" id="miboton" value="Eliminar" onclick="miFuncion()" />
<div id="res" style="color:green">
	<h3 style="color:green">@ViewBag.resultado</h3>
</div>

<script type="text/javascript">
	function miFuncion() {	
			var id = $("#id").val();
			$.ajax({
				type: "Post",
				url: "/Archivos/deleteDir?id=" + id,
				contentType: "html",				
								
			})
			$('#res').html('<strong><h2>La accion ha sido completada, recargue la pagina</h2></strong>');
	}
</script>

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/Exito.cshtml
<h2>EXITO</h2>

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
	<title>Bootstrap Example</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container">
		<!-- Trigger the modal with a button -->
		<div class="btn-group">
			<button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">Crear Directorio</button>
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mysub">Subir Archivo</button>
			<button class="btn btn-danger" onclick="location.href='@Url.Action("EliminarCarpeta", "Archivos")';return false;">Eliminar Directorio</button>
		
		</div>
			<!-- Modal -->
			<div class="modal fade" id="myModal" role="dialog">
				<div class="modal-dialog">
					<!-- Modal content-->
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h4 class="modal-title">Crear Directorio</h4>
						</div>
						<div class="modal-body">
							@{
								//se llama a la vista parcial que crea un directorio todos los directorios
								Html.RenderAction("_CrearDir", "Archivos");
							}
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-warning" data-dismiss="modal">Cancelar</button>
						</div>
					</div>

				</div>
			</div>

		</div>



	<div class="container">
		<div class="row">
			<div id="jstree-tree" class="well col-sm-3"></div>
			<div id="jstree-result" class="col-sm-6">
					<h4>Lista de Archivos en este directorio</h4>
					<div id="act">

					</div>

				</div>
		</div>
	</div>

	<div id="act">

	</div>

</body>
<script>
	var idDatos;
	$(function () {
		$('#jstree-tree').jstree({
			'core': {
				'data': {
						"url": "@Url.Action("llamarjson", "Archivos")",
					"dataType": "json" // needed only if you do not supply JSON headers
				}
			}
		});
	});
	$(function () {
		$('#jstree-tree')
			.on('changed.jstree', function (e, data) {
				var objNode = data.instance.get_node(data.selected);
				$('#jstree-result').html('Detalles del Directorio: <br/><strong>' + 'Id Del Directorio:   ' + objNode.id + '<br/> Nombre Directorio: ' + objNode.text +'</strong>');
				idDatos = objNode.id;
				$.ajax({
					type: "Get",
					url: "/Archivos/_solicitudArchivo?idDatos=" + idDatos,
					contentType: "html",
					success: function (response) {
						$("#act").html(response);
					}
				})
			})

	});

	
	$(function () {
		$("#jstree-resul").change(function () {
			var id = $(this).val();
			$.ajax({
				type: "Get",
				url: "/Archivos/_solicitudArchivo?idDatos=" + idDatos,
				contentType: "html",
				success: function (response) {
					$("#act").html(response);
				}
			})


		})
	})

</script>

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/_CrearDir.cshtml
@model EstructurasDatosProyecto2.Models.DirectoriosModelo
<script src="~/Content/admin-lte/js/jquery.min.js"></script>
@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.padre, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@if (ViewBag.listaDirectorios != null)
				{
					@Html.DropDownListFor(model => model.id, ViewBag.listaDirectorios as SelectList, "-----Seleccionar Directorio", new { @class = "form-control" })


				}

			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Guardar" class="btn btn-success" />
			</div>
		</div>
	</div>
}

<script>
	$(document).ready(function () {
		$("#id").change(function () {
			var id = $(this).val();
			$.ajax({
				type: "Post",
				url: "/Archivos/temp?id="+id,
			})


		})
	})
</script>

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/_EliminarDirectorio.cshtml
@model EstructurasDatosProyecto2.Models.DirectoriosModelo
<script src="~/Content/admin-lte/js/jquery.min.js"></script>
@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.padre, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@if (ViewBag.listaDir != null)
				{
					@Html.DropDownListFor(model => model.nombre, ViewBag.listaDir as SelectList, "-----Seleccionar Directorio", new { @class = "form-control" })

				}

			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" id="btndelete" value="Eliminar" class="btn btn-warning" />
			</div>
		</div>
	</div>
}

<script>
	$(document).ready(function () {
		$("id").dblclick(function () {
			alert("Se ha hecho doble click sobre el Div.");
		});
	});
</script>

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/_GetDirectorios.cshtml
@model IEnumerable<EstructurasDatosProyecto2.Models.DirectoriosModelo>


<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Gestion de Archivos</title>
	<link href="~/Content/arbol/file-explore.css" rel="stylesheet" type="text/css">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	</style>
</head>
<body>
	<table class="table">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.nombre)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.padre)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.estado)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.fecha_creacion)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.nombre)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.padre)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.estado)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.fecha_creacion)
				</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new { id = item.id }) |
					@Html.ActionLink("Details", "Details", new { id = item.id }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.id })
				</td>
			</tr>
		}

	</table>
	<style>
		body {
			font-family: Arial, Helvetica, sans-serif;
		}
	</style>


	<div class="container">
		<h1>Lista de Directorios</h1>
		<ul class="file-tree">
			<li>
				<a href="#">Raiz</a>
				<ul>
					<li>
						<a href="#">Raiz 2</a>
					</li>
					
				</ul>
			</li>
		</ul>
	</div>
	<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
	<script src="~/Content/arbol/file-explore.js"></script>
	<script>
$(document).ready(function() {
            $(".file-tree").filetree();
	        });
	</script>
</body>

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/_ListarDirectorios.cshtml
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Gestion de Archivos</title>
	<link href="~/Content/arbol/file-explore.css" rel="stylesheet" type="text/css">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	</style>
</head>
<body>
	<style>
		body {
			font-family: Arial, Helvetica, sans-serif;
		}
	</style>


	<div class="container">
		<h1>Lista de Directorios</h1>
		<ul class="file-tree">
			<li>
				<a href="#">US</a>
				<ul>
					<li>
						<a href="#">New York</a>
						<ul>
							<li>
								<a href="#">Corporation</a>
								<ul>
									<li> <a href="#link5">Link 5</a> </li>
									<li> <a href="#link6">Link 6</a> </li>
									<li> <a href="#link7">Link 7</a> </li>
									<li> <a href="#link8">Link 8</a> </li>
									<li>
										<a href="#">Deeper</a>
										<ul>
											<li><a href="#">Link 1</a> </li>
											<li><a href="#">Link 2</a> </li>
											<li><a href="#">Link 3</a> </li>
											<li><a href="#">Link 4</a> </li>
										</ul>
									</li>
								</ul>
							</li>
							<li>
								<a href="#">LLC</a>
								<ul>
									<li> <a href="#link5">Link 5</a> </li>
									<li> <a href="#link6">Link 6</a> </li>
									<li> <a href="#link7">Link 7</a> </li>
									<li> <a href="#link8">Link 8</a> </li>
									<li>
										<a href="#">Deeper</a>
										<ul>
											<li><a href="#">Link 1</a> </li>
											<li><a href="#">Link 2</a> </li>
											<li><a href="#">Link 3</a> </li>
											<li><a href="#">Link 4</a> </li>
										</ul>
									</li>
								</ul>
							</li>
						</ul>

					</li>
					<li><a href="#link2">Link 2</a> </li>
					<li><a href="#link3">Link 3</a> </li>
					<li><a href="#link4">Link 4</a> </li>
				</ul>
			</li>
			<li>
				<a href="#">Canada</a>
				<ul>
					<li><a href="#">Link 1</a> </li>
					<li><a href="#">Link 2</a> </li>
					<li><a href="#">Link 3</a> </li>
					<li><a href="#">Link 4</a> </li>
				</ul>
			</li>
		</ul>
	</div>
	<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
	<script src="~/Content/arbol/file-explore.js"></script>
	<script>
$(document).ready(function() {
            $(".file-tree").filetree();
	        });
	</script>
</body>
</html>

EstructurasDatosProyecto2/EstructurasDatosProyecto2/Views/Archivos/_solicitudArchivo.cshtml
@model IEnumerable<EstructurasDatosProyecto2.Models.ArchivoModelo>

@{
	if (Model != null)
	{

		<table class="table">
			<tr>
				<th>
					@Html.DisplayName("Nombre")
				</th>
				<th>
					@Html.DisplayName("Tipo de Archivo")
				</th>
				<th>
					@Html.DisplayName("Fecha de Creacion")
				</th>
				<th>
					@Html.DisplayName("Acciones")
				</th>
				<th></th>
			</tr>

			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.nombre)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.tipo)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.fecha_creacion)
					</td>
					<td>
						@Html.ActionLink("Compartir", "Delete", new { id = item.id })
						@Html.ActionLink("Descargar", "Descargar", new { id = item.id }) |
						@Html.ActionLink("Detalles", "Details", new { id = item.id }) |
						@Html.ActionLink("Eliminar", "Delete", new { id = item.id })
					</td>
				</tr>
			}

		</table>

	}
	else
	{
		<h2 style="color:red">No hay archivos en este directorio</h2>
	}

}